spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
    database-platform:  org.hibernate.dialect.PostgreSQLDialect

